### ISSUE TITLE
Some Ideas for Milestones

### ISSUE THREAD

**Issue by avgagliardo** [ubsuny/CP1-24-HW2#1]
I have a few ideas for potential milestones:

- Team/Task Pairing - The goal is to match (in a general sense) who will work on what-- code, docs, testing, maintaining, etc

- Project Architecture - The goal is to determine where files should be arranged and interface with each other
- Functionality - Implementation of the project's core functionality
- Unit Testing - Confirmation that each isolated unit (the smallest testable piece of code) performs as expected
- Integration Testing- Similar to unit testing, but with the focus placed on making sure that the code behaves properly when used together instead of as individual units. We may be able to roll this into the Unit Testing milestone for this homework task.
- Documentation - The goal would be to document the conceptual background (physics related), the software (code related), and its operational routine (user execution related)
- Version Control Strategy - Deciding on a set of standards for how we will maintain and merge the different branches.
- Code Review - The goal would be to use peer review to ensure code quality, drive participation, and catch bugs before they are merged.
- Performance Optimization - Make existing code as performant as possible

Some of these may be better addressed by creating a new issue with a corresponding label, but I just wanted to brainstorm some ideas so that we had something tangible as a jumping-off point. 

Open to all other suggestions/edits as well!

**Comment by HeshamElsaman** [comment]
Would it be professional to have the types of the operations we need to test as milestones?

**Comment by avgagliardo** [comment]
That might lead to a lot of milestones. It might be better to use a single testing milestone and then assign corresponding operation tests to that milestone as they become needed/completed.

But there's no right or wrong way to do it in general.

**Comment by laserlab** [comment]
My original idea was to have at least one milestone per algorithm, so it is clear what happens to each.

**Comment by iglesias-cardinale** [comment]
I also thought it would be a good idea to have a milestone for every algorithm. Is there a way to make milestones prior to assigning an issue? That way somebody could get them all set up.

**Comment by laserlab** [comment]
Everybody should be able to make a milestone

**Comment by kylemasc917** [comment]
I've added an organization label referenced in Issue #6 as well as left that issue open for further discussion of useful labels and opened an issue letting individuals volunteer for different implementations that can later be condensed into a markdown file for ease of access.

**Comment by kylemasc917** [comment]
Should some milestones be constructed with due dates as a way to structure the workflow of the overall project?

**Comment by avgagliardo** [comment]
Sounds like we want to use milestones per algorithm/functional unit. I'll close this issue since it seems like we have a general consensus.

**Comment by dnxjay** [comment]
Anychance we could keep this open still? Theres some good content here that could be opened up for more interaction
