### ISSUE TITLE
Handling garbage collection

### ISSUE THREAD

**Issue by iglesias-cardinale** [ubsuny/CP1-24-HW2#13]
I ran into an issue with garbage collection when running the matrix multiplication script in PR #4 on my local computer. I saw striations in my data (image attached) that (I think) arose because Python's built in garbage collection was impacting the calculation time for the matrix multiplication. 

Interestingly, this issue did not pop up when I ran this on the github codespace, so I wonder if github handles garbage collection differently. 

Regardless, I think it might be good to add some documentation about this problem and how to get around it. Using the timeit function seems to be the best option I've found so far.

![matmul output](https://github.com/user-attachments/assets/df691c7a-f3de-40d3-b02a-436ce1dfbc79)

**Comment by kylemasc917** [comment]
please add a milestone to this.

**Comment by kylemasc917** [comment]
Good idea, feel free to add the documentation yourself if no one else does.

**Comment by iglesias-cardinale** [comment]
I noticed something else that might be interesting with this in PR #22. In this case, there seem to be some sort of large vertical spread (first image). I figure this could also be due to garbage collection running up the calculation time. When I increased the number of runs timeit averages over (500 vs 50) the vertical spread was somewhat mitigated (second image ).

![Array Axis Summation Time Scaling](https://github.com/user-attachments/assets/5e38a961-1eed-4b1b-a59a-d43c792b2a95)
![Array Axis Summation Time Scaling timeit 500](https://github.com/user-attachments/assets/e0f97b11-59d5-400a-9e04-0468e52ba792)

**Comment by laserlab** [comment]
is this on a codespace using timeit?

**Comment by iglesias-cardinale** [comment]
@laserlab yes. The original issue was on my local computer but the update is on codespace using timeit.

**Comment by laserlab** [comment]
So how do you get the different run numbers? Using different n parameter for time it?

**Comment by iglesias-cardinale** [comment]
That's correct, yes. In my code I can directly implement the number of runs (n) timeit times and averages. So in the first plot in my comment I had an n-value of 50. In the second I had an n value of 500.

**Comment by iglesias-cardinale** [comment]
Closing since documentation was added.
