### ISSUE TITLE
Reviewer Assignments

### ISSUE THREAD

**Issue by kylemasc917** [ubsuny/CP1-24-HW2#14]
Since everyone is required to review at least one pull request we can go about this in one of two ways.

1. Individuals volunteer to review pull requests and we can even have more than one person review each request as well as multiple requests in order to have more oversight, but this requires full cooperation and participation from everyone.

2. I can put everyone's username in a hat and dole out reviews at random. This removes the awkward need of people to volunteer but it doesn't give people the freedom of choice on what they review.

Also, any suggestions for ways of refining these further are welcome as well as spirited debate over what we should do as reviewing can come later. People should focus on choosing their task and submitting their own pull requests for now.

**Comment by avgagliardo** [comment]
I was going to say I'll take the next one but it looks like I've been assigned one already. If there is overflow I'll take some of those, but there should be enough PRs to spread the fun around.

**Comment by ojha-aditya** [comment]
I am a little confused about this part, so how exactly would the review process work since there is one or maybe 2 maintainers. Does everyone who review a PR, then let the maintainer know about it in the end, once all conversations in there are resolved?

**Comment by kylemasc917** [comment]
Once you are formally requested to review you can check the review box at the bottom of the PR and that unlocks the pull request for merging.

**Comment by dnxjay** [comment]
I like the idea of you assigning them. Looks like i already have been assigned one so i will take a look at it

**Comment by haiderabbas007** [comment]
What's the protocol for reviewing a pull request?

**Comment by avgagliardo** [comment]
We were talking about this a little bit in #24

**Comment by dnxjay** [comment]
PR #34 needs reviewing if anyone up for it before its assigned
