### ISSUE TITLE
Potential idea about PR Reviews

### ISSUE THREAD

**Issue by ojha-aditya** [ubsuny/CP1-24-HW2#16]
Would it be a good idea to create the .md file about who is doing what tasks first as was discussed in #5, so that when it comes to review the PRs, it would be more convenient. That way, people working on the same tasks could then review PR for each other. 
For example me and @iglesias-cardinale can review the PRs for each other if we both work on Matrix multiplication, this could also help to reduce the number of files in the repository as there can been code per task.

**Comment by kylemasc917** [comment]
I am working on that file now it should be up by end of day today.

**Comment by ojha-aditya** [comment]
Closing this as we are nearing the deadline now.
