### ISSUE TITLE
Understanding the required

### ISSUE THREAD

**Issue by HeshamElsaman** [ubsuny/CP1-24-HW2#18]
I have two questions:

1. Are we required to use Einstein notation with all the listed implementations? Because, for example, I don't know how to use that with broadcasting.
2. How exactly are we required to report the execution times of the different operations and compare them? (I added a separate file in PR #17 if that would help you answer my question and clear my confusion)

**Comment by avgagliardo** [comment]
> I have two questions:
> 
> 1. Are we required to use Einstein notation with all the listed implementations? Because, for example, I don't know how to use that with broadcasting.
> 2. How exactly are we required to report the execution times of the different operations and compare them? (I added a separate file in PR [Added the .devcontainer directory (to setup the codespace for Python) #17](https://github.com/ubsuny/CP1-24-HW2/pull/17) if that would help you answer my question and clear my confusion)

With respect to your second question, I plan on storing my tests in another file named efficiency_tests.py or performance_tests.py or something like that. Initially I was going to put them alongside my unit tests, but I think it might be better off in a separate file where it can be explicitly documented-- not to mention we could probably write as many (if not more) performance tests than unit tests by the end of the project.

As for reporting, I typically output results to the terminal during execution (for my own convenience) and save the results to a dynamically named file (to avoid accidental overwriting old ones) for analysis. I tend to analyze the data separately, so I split that off into its own functionality. We can worry about standardizing the data outputs later on as long as we all understand what happens to data/where it goes during execution.

We may also be interested in capturing a few key pieces of information like **execution time**, **memory usage**, **time/space complexity**, **energy cost**, etc-- the list goes on and on...
