### ISSUE TITLE
Confused about documentation and implementing code

### ISSUE THREAD

**Issue by Cosmos491** [ubsuny/CP1-24-HW2#19]
I am having some confusion as to the distribution of tasks since I chose Tensor contractions. Do I need to work on documentation and the implementation of the code regarding the comparison of run times for them, or just choose one of them ?

**Comment by HeshamElsaman** [comment]
I believe it would be best, as long as the implementation is not shared between multiple people, for each one of us to be responsible for the implementation and documentation of a single algorithm. However, that's only to my personal opinion. I guess we need to reach some consensus on that matter.

**Comment by kylemasc917** [comment]
Please add a milestone to this.

**Comment by dnxjay** [comment]
I believe that we are responsible for both documentation and implementation. It might be useful to bounce ideas if multiple people are working on the same task
