### ISSUE TITLE
Regarding implementations 

### ISSUE THREAD

**Issue by Priyanka-43** [ubsuny/CP1-24-HW2#2]
For each student, on how many implementations will he/she work?

**Comment by abruns123** [comment]
It seems that each student will work on one implementation. Since there are more implementations than students, some will work together on one implementation. Others may be alone but we'll all be able to look over each other's code to report issues.

**Comment by Priyanka-43** [comment]
Sure, Thankyou.

**Comment by dnxjay** [comment]
Thats correct, just one implementation per student but feel free to one with multiple people.
