### ISSUE TITLE
Organization of Code

### ISSUE THREAD

**Issue by iglesias-cardinale** [ubsuny/CP1-24-HW2#23]
Should we keep adding new files for the implementation of algorithms in our pull requests and later someone can put them all into one file? Or should we just update matrix_operations.py with each new pull request as we go?

I'm cool with whatever works best for everyone, but in my opinion it would be best to upload separate files. That way, at the end, whoever compiles everything into matrix_operations.py can format it in a consistent way. This might be a big enough project for someone's entire homework task.

**Comment by haiderabbas007** [comment]
I agree that uploading separate files is better, but since no one has apparently accepted the task yet, should we go with the other option?

**Comment by laserlab** [comment]
Either way works since it is not that much code. Ideally would be a separation of algorithm and benchmarking. @haiderabbas007  why don’t you do this then?

**Comment by haiderabbas007** [comment]
Also, can you please provide a few guidelines for this task?

**Comment by laserlab** [comment]
For each algorithm separate it to a function and then make a new function that does the benchmarking.

**Comment by laserlab** [comment]
Basically a wrapper for timeit as they show at the bottom of: https://docs.python.org/3/library/timeit.html
