### ISSUE TITLE
We need 7 more milestones

### ISSUE THREAD

**Issue by iglesias-cardinale** [ubsuny/CP1-24-HW2#26]
To get the full number of homework points we need 18 total milestones. We only have 11 right now, so we need 7 more.  Maybe we could add one for documentation on each algorithm we're implementing. With 9 total algorithms that should get us to where we need to be.

**Comment by avgagliardo** [comment]
Good idea! I just made a new one too that we can use for testing/checking off that code is executing properly.

https://github.com/ubsuny/CP1-24-HW2/milestone/12

**Comment by ojha-aditya** [comment]
Should we still make these? There are 3 more to go it seems.

**Comment by avgagliardo** [comment]
Yeah, I am still brainstorming. We will get them though!

**Comment by kylemasc917** [comment]
I have created three more milestones to meet the goal, but they can be deleted and edited if better ones come about between now and the deadline.

**Comment by iglesias-cardinale** [comment]
Sounds good, thank you. I'll close the issue for now.
