### ISSUE TITLE
Clarification for HW task

### ISSUE THREAD

**Issue by Priyanka-43** [ubsuny/CP1-24-HW2#33]
@laserlab Will each individual be responsible for everything related to the HW problem?
I mean should i do documentation and docstrings, code, unit test and code for inner and outer product or just choose one task??

**Comment by p-pxmpo** [comment]
I also have the same question thanks

**Comment by dnxjay** [comment]
Thats a good question. Maybe @kylemasc917 might have the answer to?

**Comment by laserlab** [comment]
For a homework task you only have to do either documentation, algorithm or unit test. Be aware though that all of them needs a comparison between diffent implementations. As described in https://github.com/ubsuny/CompPhys/blob/main/ReviewPython/EinsteinNotation.ipynb which is linked in the homework description

**Comment by Priyanka-43** [comment]
Ok.
