### ISSUE TITLE
Documentation Ideas

### ISSUE THREAD

**Issue by dnxjay** [ubsuny/CP1-24-HW2#39]
Does the documentation have to be specific to tasks that we are working on or can we also add documentation which pertains to something else that someone else is working on?

**Comment by avgagliardo** [comment]
With respect to files and where documentation lives, I would say try to keep all the documentation relevant to whatever the file name/content indicates. 

As for extra information, there's definitely no harm in including it! Good places for it to live might be in a separate file that is named after what kind of information it holds (filenames that self-describe their content/purpose are the best, and will make you a very popular and effective developer)-- or maybe even at the end of the central project documentation, but as part of an appendix at the end.

**Comment by ojha-aditya** [comment]
In the end of the project are we again aiming for a single documentation file like in previous HW?

**Comment by dnxjay** [comment]
the a good question, im assuming yes but not completely sure on this one
