### ISSUE TITLE
Regarding LateX

### ISSUE THREAD

**Issue by Priyanka-43** [ubsuny/CP1-24-HW2#44]
I am using Latex for documentation of my task. 
$\displaystyle\vec{{a}}\cdot\vec{{b}}={\sum_{{{i}={1}}}^{{n}}}{a}{{i}}{b}{{i}}$
$\displaystyle\vec{{a}}\cdot\vec{{b}}={a}{{i}}{b}^{i}$
There are more equations like this which are not working. Can anyone help me in this?

**Comment by laserlab** [comment]
can you describe what is not working?

**Comment by haiderabbas007** [comment]
Try these: 

\vec{a} \cdot \vec{b}=\sum_{i=1}^n a_i b_i   ====== $\vec{a} \cdot \vec{b}=\sum_{i=1}^n a_i b_i$

\vec{a} \cdot \vec{b}= a_i b^i  ======== $\vec{a} \cdot \vec{b}= a_i b^i$

**Comment by Priyanka-43** [comment]
@laserlab What I have written in my first comment. It's working here, but not in my documentation.

**Comment by laserlab** [comment]
> Try these:
> 
> \vec{a} \cdot \vec{b}=\sum_{i=1}^n a_i b_i ====== a → ⋅ b → = ∑ i = 1 n a i b i
> 
> \vec{a} \cdot \vec{b}= a_i b^i ======== a → ⋅ b → = a i b i

As I said before I also think that less brackets and unnecessary display styles would help to trouble shoot. But it renders in the comment.

**Comment by Priyanka-43** [comment]
https://github.com/Priyanka-43/CP1-24-HW2/blob/8cf9b6697b045ce58080ace423a326512b209847/documentation/InnerandOuterProduct.md

**Comment by Priyanka-43** [comment]
I have tried to use this equation as well.
[ C = a \times b = a_i b_j = \begin{pmatrix} a_1 b_1 & a_1 b_2 & \cdots & a_1 b_n \ a_2 b_1 & a_2 b_2 & \cdots & a_2 b_n \ \vdots & \vdots & \ddots & \vdots \ a_m b_1 & a_m b_2 & \cdots & a_m b_n \ \end{pmatrix} ]

**Comment by Priyanka-43** [comment]
It is also not showing required equation.

**Comment by laserlab** [comment]
```latex
$\vec a \cdot\vec b = \sum_i= 1^n a_i b_i$
```
Works for me

**Comment by laserlab** [comment]
So remove all the unnecessary brackets

**Comment by laserlab** [comment]
for the future: To troubleshoot add each part of the equation one by one till it fails then investigate why it fails

**Comment by Priyanka-43** [comment]
Ok Professor.
