### ISSUE TITLE
Early Organization of tasks

### ISSUE THREAD

**Issue by kylemasc917** [ubsuny/CP1-24-HW2#5]
Just opening an issue where everyone can express what task from the listed implementations they would like to tackle just as a starter to get a feel for how to spread the work.

1. Trace of an array
2. Return a diagonal
3. Array axis summations
4. Transpositions and permutations
5. Matrix multiplication and dot product
6. Vector inner and outer products
7. Broadcasting, element-wise and scalar multiplication
8. Tensor contractions
9. Chained array operations, in efficient calculation order

I will put the responses to this in a markdown file so everyone can cross reference it once people start getting into the swing of it.
Try to pick one someone hasn't already chosen but there will be overlap so it's not the end of the world if more than one person is working on the same thing.

**Comment by Priyanka-43** [comment]
I will do vector inner and outer product.

**Comment by avgagliardo** [comment]
I will do return of a diagonal and I'll also write it's unit tests.

**Comment by dnxjay** [comment]
I will do Trace of an array

**Comment by Cosmos491** [comment]
I will do the tensor contractions

**Comment by ojha-aditya** [comment]
I am willing to do the Matrix Multiplication and dot product part.

**Comment by avgagliardo** [comment]
Referencing issues #7, #10,  and #11 which address this matter

**Comment by Cosmos491** [comment]
I am taking an example from General Relativity and try to explain the Tensor contractions and the code Implementation of Ricci Scalar Calculation Using Einstein Notation.

**Comment by HeshamElsaman** [comment]
I'll work on 7 (Broadcasting, element-wise and scalar multiplication).

**Comment by iglesias-cardinale** [comment]
5. @ojha-aditya I've already implemented some code in PR #4 that times some matrix multiplication. Maybe you can add something in there to implement the dot product?

**Comment by abruns123** [comment]
I can work on #6 vector inner and outer products

**Comment by ojha-aditya** [comment]
Sounds like a good idea @iglesias-cardinale I will open a separate issue wherein all matrix multiplication related information can be discussed and organized. And create a milestone for the same.

**Comment by dhamalakamal** [comment]
I will be doing Matrix multiplication and Dot Product

**Comment by HeshamElsaman** [comment]
Would I suggest that each person working on an implementation is to be encouraged to also work on its documentation? (We just need to agree on a global format)

**Comment by ojha-aditya** [comment]
That sounds like a good idea, maybe we can start with a separate markdown file initially and closer to deadline some common format can be agreed upon?

I will write the one for Matrix Multiplication soon

**Comment by dhamalakamal** [comment]
I agree with @ojha-aditya

**Comment by kylemasc917** [comment]
I have added the assignment listing. I agree that those who volunteer for each task should handle the implementation and documentation themselves unless they can agree to split it withanother.

**Comment by jkblc** [comment]
I can do 4 transpositions and permutations. It might be a good one to split with someone else as well.

**Comment by p-pxmpo** [comment]
3

**Comment by haiderabbas007** [comment]
What are the guidelines as to what should be included (e.g., level of detail, etc.) in the documentation of each task?
