### ISSUE TITLE
Default project configuration codespace

### ISSUE THREAD

**Issue by ojha-aditya** [ubsuny/CP1-24-HW2#50]
Has anyone tried installing some packages directly using the CodeSpace terminal and then pulling some code from that codespace? I remember @laserlab had advised against this as then not everyone will have the same environment, but I was just curious as to what the Default configuration supports, so that in case someone uses something like this, how likely is it to run on another codespace?

**Comment by avgagliardo** [comment]
project actions/automations solve this problem by letting you specify a certain build env and routine, then every time you push it will try to build that env to test it for compatibility.

Doing it specifically in the codespace might lead to difficulties in terms of tracking what is installed and which system it actually lives on, but if you understand how the container virtualization works then there's no magic there.

**Comment by ojha-aditya** [comment]
I see, is there a documentation/resource about this that discusses in depth?

**Comment by laserlab** [comment]
we will do this in class soon

**Comment by ojha-aditya** [comment]
Great! closing this then.
