### ISSUE TITLE
Editing milestones

### ISSUE THREAD

**Issue by ojha-aditya** [ubsuny/CP1-24-HW2#54]
@laserlab can we edit the milestones other than the Homework due date one to incorporate the changes in the former?

**Comment by laserlab** [comment]
yes milestones can be edited

**Comment by ojha-aditya** [comment]
Got it, will change them then.

**Comment by ojha-aditya** [comment]
Changed the one for Matrix Multiplication. Will do the remaining if not taken up by someone else.
