### ISSUE TITLE
New Labels

### ISSUE THREAD

**Issue by kylemasc917** [ubsuny/CP1-24-HW2#6]
I created a new organization label to go along with the Task Distribution Milestone so we can label issues and pull requests related to the overall organization of tasks and files. I am leaving this issue as a place for people to brainstorm any other labels that might be useful for this project.

**Comment by avgagliardo** [comment]
We might want to reuse a few of the labels we used last time. I'll take a look at the old ones and see if any are worth bringing back for this project.

**Comment by dnxjay** [comment]
I feel like we should start with the ones that we had for the last project and then maybe keep this convo open so as time goes on we can brainstorm new ones

**Comment by dnxjay** [comment]
Created a testing label!
