### ISSUE TITLE
Missing .devcontainer file

### ISSUE THREAD

**Issue by ojha-aditya** [ubsuny/CP1-24-HW2#62]
I guess after merging #30 we do not have a .devcontainer file anymore. Do we, till a new PR as discussed in #17 and #30 is created, work with a .devcontainer file from some previous in our forks or should we retain a temporary one here till a PR replacing #17 is created?

**Comment by HeshamElsaman** [comment]
I guess so. I'll be working on creating a new pull request immediately.

**Comment by abruns123** [comment]
Just reviewed and accepted the pull request.

**Comment by ojha-aditya** [comment]
Great! Will close the issue then.
