### ISSUE TITLE
Open PRs

### ISSUE THREAD

**Issue by avgagliardo** [ubsuny/CP1-24-HW2#69]
I see that there a still a lot of open PRs waiting review (16 at the moment) so I think we need to change strategies if we are going to hit the deadline.

Maybe after a certain point today/tomorrow we should just start reassigning the PR reviews to anyone who is available or else a lot of people will not be getting points.

I don't mind doing extra PR reviews, but I wont be able to review my own-- currently I have one and there will probably be 3 more coming tonight.

Anyone else want to join in and volunteer for PR review overflow duty?

**Comment by avgagliardo** [comment]
Yeah agreed, that's why maybe we should wait until tomorrow minimally.

**Comment by Priyanka-43** [comment]
I have the same query. My 3 PR are still open.

**Comment by avgagliardo** [comment]
> I have the same query. My 3 PR are still open.

I can dedicate some time tomorrow afternoon to get through a bunch of these. 

In the meantime, if you are waiting on a PR review you could also try to @ the person in the PR comments to give them a polite reminder.

**Comment by kylemasc917** [comment]
I can start dropping reminders in pull requests if they don't get reviewed by the time I get to campus tomorrow I can start adding you two to the open ones.

**Comment by Priyanka-43** [comment]
> > I have the same query. My 3 PR are still open.
> 
> I can dedicate some time tomorrow afternoon to get through a bunch of these.
> 
> In the meantime, if you are waiting on a PR review you could also try to @ the person in the PR comments to give them a polite reminder.

I have done the same.

**Comment by kylemasc917** [comment]
You have outstanding issues in the pull requests made by @laserlab that need to b fixed before they can be reviewed and merged.

**Comment by Priyanka-43** [comment]
Hi, I tried to do that.

**Comment by laserlab** [comment]
If you’re PR is waiting for review send messages with mentions to the reviewer tonight. Also if there is no response for ones open and reviewer was reminded feel free to change reviewer.

**Comment by iglesias-cardinale** [comment]
I can also do some reviewing of PRs tomorrow before the deadline if necessary.

**Comment by kylemasc917** [comment]
I will add your name to my list thank you very much.

**Comment by abruns123** [comment]
I can also review more pull requests.

**Comment by kylemasc917** [comment]
Excellent I shall add you as well.

**Comment by avgagliardo** [comment]
I'll leave this thread open until tomorrow in case anybody else wants to volunteer, then I'll close it.

**Comment by kylemasc917** [comment]
I have added all of you that volunteered to do extra reviews to the pull requests that need them. I tried to spread them out evenly. Feel free to do so when you get the chance.
