### ISSUE TITLE
Einsum not working as expected with complex numbers

### ISSUE THREAD

**Issue by abruns123** [ubsuny/CP1-24-HW2#76]
So, I'm doing vector inner and outer products and of course, to do that, the inner product involves the complex conjugate of the first vector whereas the outer product involves the complex conjugate of the second vector. However, when given two vectors, einsum doesn't appear to take the complex conjugate for either vector for inner or outer products. I've gotten around it for now by looping through the corresponding vector for the inner/outer product to take the complex conjugate of each element before applying einsum, but is there an alternative einsum function out there that might amend this more simply? Like how numpy.dot(v1, v2) doesn't take the complex conjugate of v1 but numpy.vdot(v1,v2) does?

**Comment by ojha-aditya** [comment]
Maybe you can try using numpy.conjugate() when you pass the matrix/vectors in Einsum.

**Comment by abruns123** [comment]
Oh cool. Didn't know np.conjugate could work with the whole vector at once. Thanks.
