### ISSUE TITLE
GitHub resources

### ISSUE THREAD

**Issue by dnxjay** [ubsuny/CP1-24-HW2#9]
Just wondering who are some of the people in here with prior experience with gitHub? I would like to learn alot more about GitHub and would be nice if anyone has some tips or found some resources that they found were helpful in learning, thank you!

**Comment by ojha-aditya** [comment]
This was a link posted on the course discord for basics of GitHub: https://docs.github.com/en/get-started/start-your-journey/hello-world

**Comment by laserlab** [comment]
https://docs.github.com/en/get-started/start-your-journey/hello-world

**Comment by avgagliardo** [comment]
> Just wondering who are some of the people in here with prior experience with gitHub? I would like to learn alot more about GitHub and would be nice if anyone has some tips or found some resources that they found were helpful in learning, thank you!

I've got a little experience but I am still learning as well. If I see questions in the issues sections I try to answer them and follow up with some documentation for anyone who has more questions, so feel free to post any questions you have!  The github label makes them especially easy to spot.

**Comment by dnxjay** [comment]
Thanks for the link guys

**Comment by haiderabbas007** [comment]
Here's a good starting point: https://www.youtube.com/watch?v=RGOj5yH7evk
