### ISSUE TITLE
Multiple PR

### ISSUE THREAD

**Issue by dnxjay** [ubsuny/CP1-24-HW2#95]
So i'm still trying to understand GitHub better, doing research, i encountered that you cant do multiple PR under the same branch before its merged? Assuming that true, how am i supposed to reach the goal of 5 PR if i haven't had my first one merged yet?

**Comment by jkblc** [comment]
You just have to make another branch in your fork and open a PR from there.

**Comment by dnxjay** [comment]
Thank You think i figured it out
